### PR TITLE
Updated the ansible lint check workflow file

### PR DESCRIPTION
**Pull request by Sakethanne**
fix(workflow): updated the ansible lint check workflow file

### CODE REVIEW

**Review by glimchb — CHANGES_REQUESTED** [review]
why not
```
              - name: run-ansible-lint
                uses: ansible/ansible-lint@v24.9.2
```
first ?


see https://ansible.readthedocs.io/projects/lint/installing/#installing-ansible-lint-as-a-github-action

and warning
```
A new release of ansible-lint is available: 24.5.0 → 24.9.2
```

**Comment by Sakethanne** [comment]
I tried that initially, but it is still unable to recognize the installed collections. with the new script we do not need to specify the version, as it automatically picks up the latest version available

**Comment by glimchb** [comment]
> I tried that initially, but it is still unable to recognize the installed collections. with the new script we do not need to specify the version, as it automatically picks up the latest version available

maybe we need to pass argument like
```
requirements_file: Path to the requirements.yml file to install role and collection dependencies.
```

**Comment by Sakethanne** [comment]
when I try to install the collections, it says they are already installed
```
Run ansible-galaxy collection install arista.eos
  ansible-galaxy collection install arista.eos
  ansible-galaxy collection install community.general
  ansible-galaxy collection install f5networks.f5_modules
  ansible-galaxy collection install community.docker
  shell: /usr/bin/bash -e {0}
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
```

**Comment by Sakethanne** [comment]
I initially added this as a part of the code:

```
# Install required Ansible collections
      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install arista.eos
          ansible-galaxy collection install community.general
          ansible-galaxy collection install f5networks.f5_modules
          ansible-galaxy collection install community.docker
```
then removed it, since they are already installed

**Comment by glimchb** [comment]
> I initially added this as a part of the code:
> 
> ```
> # Install required Ansible collections
>       - name: Install Ansible collections
>         run: |
>           ansible-galaxy collection install arista.eos
>           ansible-galaxy collection install community.general
>           ansible-galaxy collection install f5networks.f5_modules
>           ansible-galaxy collection install community.docker
> ```
> 
> then removed it, since they are already installed

but this https://ansible.readthedocs.io/projects/lint/installing/#installing-ansible-lint-as-a-github-action clearly states
```
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: ""
          setup_python: "true"
          working_directory: ""
          requirements_file: ""
```

I would try new `requirements_file` argument

**Comment by Sakethanne** [comment]
Let me try the new option and get back with the results of it soon

**Pull request closed without merging**
